### ISSUE TITLE
Support for abstracts

### ISSUE THREAD

**Issue by foscraig** [EronHennessey/db2rst#1]
db2rst takes the text in abstract and puts at the top of the resultant rst file. I'm not exactly sure how to handle this but it would either be nice to suppress or put somewhere else.

**Comment by EronHennessey** [comment]
Thanks Craig, I'll update this when I've got a fix!

**Comment by EronHennessey** [comment]
Done! :) If you clone (or pull) the repo and use the setup script to install, you'll get the update. I'm not going to update PyPi until the other issues are fixed.

The implementation takes any <para> or <simpara> elements in the <abstract> and turns them into an HTML meta "description" for the resulting file. You'll see it in the reST document as a '.. meta::' directive, but when you convert it to HTML, it'll be hidden in the HTML metadata.

More info:
- [reST meta directive](http://docutils.sourceforge.net/docs/ref/rst/directives.html#meta)
- [HTML meta tag](http://www.w3schools.com/tags/tag_meta.asp)
